### ISSUE TITLE
Fix second BSON-too-large error when migrating large docker contents

### ISSUE THREAD

**Issue by ggainey** [pulp/pulp-2to3-migration#583]
**Version**
0.11+

**Describe the bug**
A second place where requesting "all" from mongo generates a too-large result.

**To Reproduce**
See https://github.com/pulp/pulp-2to3-migration/pull/579#issuecomment-1223686546 for details.

**Comment by dralley** [comment]
re: https://bugzilla.redhat.com/show_bug.cgi?id=2118537
